{% set name = "apache-atlas" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-atlas-{{ version }}.tar.gz
  sha256: d853460728f1a6cafe0510c97701d8d761f4a3b55d8c852c7c0af470c026ce5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=2.24

test:
  imports:
    - apache_atlas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/atlas/tree/master/intg/src/main/python
  summary: Apache Atlas Python Client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
