# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: apache-atlas
  version: "0.0.16"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_atlas-${{ version }}.tar.gz
  sha256: 926fddaa080aa4f2c4cb787763eb3426aa972100ad7e4f2e3f8f3cfdae52d450

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - requests >=2.24

tests:
  - python:
      imports:
        - apache_atlas
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Apache Atlas Python Client
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/apache/atlas/tree/master/intg/src/main/python

extra:
  recipe-maintainers:
    - rxm7706
